### PR TITLE
Detect Ubuntu release after (and including) 16.04 LTS

### PR DESCRIPTION
**Pull request by g0wfv**

### CODE REVIEW

**Comment by g0wfv** [comment]
Hmmm didn't want to add all the changes!  I'll close this and see if I can generate a PR with just my change!

**Comment by Romeo-Golf** [comment]
No this is my bad for not having at least merged the changes from the upstream master to my 2.7.0, which I should have fixed shortly ;)

**Comment by g0wfv** [comment]
Are you able to merge from this PR, as I'm having issues generating the PR this end (inexperience with git!)

**Comment by Romeo-Golf** [comment]
Hmm, I have now merged the various small changes from the upstream master so looks good to merge this... with some tweaks to fit with the coding style etc :)

I concur that there is a steep learning curve for a lot of the branching and merging features on github, having myself inadvertently merged my dev code into a stable branch when I meant to do the opposite..

But it seems like you have the right idea with creating dedicated branches for minor fixes to allow for clean merges, assuming of course I keep my branches at least in sync with the upstream master ;)

**Comment by Romeo-Golf** [comment]
The merge seems to have gone to plan, I will try to test on an ubuntu 16.10 install and if successful will manually merge the changes into my 2.6.0 branch.... and from there hopefully into @jprochazka 's 2.6.0 release :)

Thanks again for the contribution.

**Comment by g0wfv** [comment]
You're welcome - they're just the changes I made to get things installing
on my own Ubuntu 16.10 system here (albeit from @jprochazka 's master branch).  Next one is to have a
go at the RPi (when I get a chance!)

Thanks to you and @jprochazka for taking
the time to streamline the installation of what (up till now) was a mildly
painful process getting everything talking!

**Comment by Romeo-Golf** [comment]
Yeah assuming it's -json on both php versions then it should be possible to at least parameterize the phone version and reuse that when specifying the packages to install :)

**Pull request merged**
